// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEPiVkvcZ9NTNVpy-FoGBgWSVeiUYPpgM',
    appId: '1:115400833864:web:791755d6313154baedd17d',
    messagingSenderId: '115400833864',
    projectId: 'lingolab-4e2f4',
    authDomain: 'lingolab-4e2f4.firebaseapp.com',
    storageBucket: 'lingolab-4e2f4.firebasestorage.app',
    measurementId: 'G-3RJLMY6Z0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1gcVt0oKomvfeuA0kkfPg20gUm2ql4h0',
    appId: '1:115400833864:android:5147e462f1640947edd17d',
    messagingSenderId: '115400833864',
    projectId: 'lingolab-4e2f4',
    storageBucket: 'lingolab-4e2f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNM3_blH5WieMPiY9zbujpiveSyyREOoM',
    appId: '1:115400833864:ios:ff02a54e924a9655edd17d',
    messagingSenderId: '115400833864',
    projectId: 'lingolab-4e2f4',
    storageBucket: 'lingolab-4e2f4.firebasestorage.app',
    iosBundleId: 'com.example.lingolab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNM3_blH5WieMPiY9zbujpiveSyyREOoM',
    appId: '1:115400833864:ios:ff02a54e924a9655edd17d',
    messagingSenderId: '115400833864',
    projectId: 'lingolab-4e2f4',
    storageBucket: 'lingolab-4e2f4.firebasestorage.app',
    iosBundleId: 'com.example.lingolab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEPiVkvcZ9NTNVpy-FoGBgWSVeiUYPpgM',
    appId: '1:115400833864:web:a58a13c64266da63edd17d',
    messagingSenderId: '115400833864',
    projectId: 'lingolab-4e2f4',
    authDomain: 'lingolab-4e2f4.firebaseapp.com',
    storageBucket: 'lingolab-4e2f4.firebasestorage.app',
    measurementId: 'G-NN1327J4BS',
  );
}
